### ISSUE TITLE
Award and display points

### ISSUE THREAD

**Issue by paltman** [pinax/patch-game#7]
Need to come up with the levels

**Comment by jtauber** [comment]
Can just do levels based on points, possibly done like Typewar

`points_required = ((level + 1) ** 3) / 4`

See https://eldarion.com/blog/2010/01/20/typewar-points-and-levels/

**Comment by jtauber** [comment]
One level question, though, is whether patches get unlocked by label.

While that's a nice feature, I think we should probably punt on it and keep the mechanism as simple as possible initially.

This probably also means just give people a fixed number of points for a correct answer (or fixed loss for wrong) rather than make it based on global stats like Typewar.

**Comment by jtauber** [comment]
Going to split this issue up. I think points, levels, leaderboards and badges can all be done separately.

**Comment by paltman** [comment]
Points are done
